version: '3'

services:
  gyrnal_web:
    image: ghcr.io/pglaum/gyrnal_web:main
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
    networks:
      - swarm-proxy

networks:
  swarm-proxy:
    external: true
